services:
  fluxity-api:
    container_name: fluxity-api
    env_file: .env
    environment:
      DB_URI: mongodb://mongo-fluxity:27016
      LOG_FILE_PATH: /app/storage/${LOG_FILENAME}
    build: .
    restart: unless-stopped
    volumes:
      - '${LOG_DIRNAME}:/app/storage'
    networks:
      - wagentapi
    ports:
      - '127.0.0.1:3000:5000'
