services:
  fluxity-api:
    env_file: .env
    environment:
      DB_URI: mongodb://mongo-fluxity
      LOG_FILE_PATH: /app/storage/${LOG_FILENAME}
    build: .
    networks:
        - fluxityapi
    restart: unless-stopped
    volumes:
      - '${LOG_DIRNAME}:/app/storage'
    ports:
      - '127.0.0.1:3000:3000'

networks:
  fluxityapi:
    name: fluxityapi
    external: true
