services:
  fluxity-api:
    container_name: fluxity-api
    env_file: .env
    environment:
      DB_URI: mongodb://mongo-wagent:27017
      LOG_FILE_PATH: /app/storage/${LOG_FILENAME}
    build: .
    restart: unless-stopped
    volumes:
      - '${LOG_DIRNAME}:/app/storage'
    networks:
      - fluxityapi
    ports:
      - '5000:5000'

networks:
  fluxityapi:
    name: fluxityapi
    external: true
